name: CI flow for Amazon ECS

on: [push]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: graphql-test-api

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.19

    - run: ls -a 
    - name: Unit Test
      run: go test -v ./...

